# Generated by Django 5.2 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(blank=True, max_length=150, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=13)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
