# Generated by Django 5.2 on 2025-04-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('emai_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('emai_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField()),
                ('duration', models.TimeField()),
                ('price', models.BigIntegerField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='course.student')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='course.teacher')),
            ],
        ),
    ]
