# Generated by Django 5.2 on 2025-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Categories',
            field=models.ManyToManyField(related_name='categories', to='course.category'),
        ),
    ]
