# Generated by Django 5.2 on 2025-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="Categories",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teachers",
        ),
        migrations.AddField(
            model_name="course",
            name="Categories",
            field=models.ManyToManyField(
                related_name="Categories", to="course.category"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(related_name="student", to="course.student"),
        ),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(related_name="teacher", to="course.teacher"),
        ),
    ]
