# Generated by Django 5.1.7 on 2025-04-10 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Categories',
        ),
        migrations.AddField(
            model_name='course',
            name='Categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='course.category'),
            preserve_default=False,
        ),
    ]
