# Generated by Django 5.1.7 on 2025-04-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_date_created2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_created2',
        ),
    ]
