# Generated by Django 5.1.7 on 2025-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
