# Generated by Django 5.1.7 on 2025-04-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_add_email_student'),
        ('course', '0009_course_add_date'),
    ]

    operations = [
    ]
